### ISSUE TITLE
Please forgive me - ELM327

### ISSUE THREAD

**Issue by rusefillc** [moonglow/pcan_cantact#10]
А нет ли возможности и желания в эту же прошивку или в другую прошивку реализовать ELM327 протокол хоть в какой-то форме?

идея - хочется USB-CDC-Serial (т.е. без RS232 где либо в цепочке от ПК до устройства, ради нативной USB контроля и коррекции ошибок) адаптер в CAN. Есть ли такие решения?

ELM327 это как раз протокол
а stm32 это вариант USB-CDC-Serial без RS232

**Comment by moonglow** [comment]
@rusefillc 
В ближайшем будущем не планирую ( я уже реализовал 5 видов адаптеров от 3-х известных производителей, что по моему мнению уже и так перебор :) ) Да и вроде ELM327 уже и так кем только не делался, а китайские клоны так вообще по 350руб за Bluetooth версию и меньше 1000руб за красивую версию с USB проводом. Грубо говоря купить дешевле чем повторят большинству пользователей.

**Comment by rusefillc** [comment]
Я пока не до конца разобрался в ELM327 клонах, но пока мне кажется что там везде отдельно чип с CAN и отдельно чип с USB, и между ними всегда или часто настоящий RS232. И у меня ощущение, что в моих настоящих тестах это уже причина боли.

Написал только что email с попыткой выйти на прямую телефонну связь, может быть я смогу проспонсировать stm32 ELM327, а может он мне и реально не нужен :)
