### ISSUE TITLE
Cannot build anything

### ISSUE THREAD

**Issue by kadirtunc** [moonglow/pcan_cantact#12]
`make BOARD=canable DEBUG=0 OPT=-Os elf hex bin
make[1]: Entering directory '/home/kadir/Downloads/pcan_cantact-master'
mkdir build-canable		
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/main.d" -Wa,-a,-ad,-alms=build-canable/main.lst Src/main.c -o build-canable/main.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/usbd_conf.d" -Wa,-a,-ad,-alms=build-canable/usbd_conf.lst Src/usbd_conf.c -o build-canable/usbd_conf.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/usbd_desc.d" -Wa,-a,-ad,-alms=build-canable/usbd_desc.lst Src/usbd_desc.c -o build-canable/usbd_desc.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/pcan_usb.d" -Wa,-a,-ad,-alms=build-canable/pcan_usb.lst Src/pcan_usb.c -o build-canable/pcan_usb.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/pcan_can.d" -Wa,-a,-ad,-alms=build-canable/pcan_can.lst Src/pcan_can.c -o build-canable/pcan_can.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/pcan_led.d" -Wa,-a,-ad,-alms=build-canable/pcan_led.lst Src/pcan_led.c -o build-canable/pcan_led.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/pcan_protocol.d" -Wa,-a,-ad,-alms=build-canable/pcan_protocol.lst Src/pcan_protocol.c -o build-canable/pcan_protocol.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/pcan_timestamp.d" -Wa,-a,-ad,-alms=build-canable/pcan_timestamp.lst Src/pcan_timestamp.c -o build-canable/pcan_timestamp.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/system_stm32f0xx.d" -Wa,-a,-ad,-alms=build-canable/system_stm32f0xx.lst Src/system_stm32f0xx.c -o build-canable/system_stm32f0xx.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_ll_usb.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_ll_usb.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_usb.c -o build-canable/stm32f0xx_ll_usb.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal_pcd.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal_pcd.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.c -o build-canable/stm32f0xx_hal_pcd.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal_pcd_ex.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal_pcd_ex.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.c -o build-canable/stm32f0xx_hal_pcd_ex.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal_rcc.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal_rcc.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c -o build-canable/stm32f0xx_hal_rcc.o
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c: In function 'HAL_RCC_MCOConfig':
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c:1018:33: warning: unused parameter 'RCC_MCOx' [-Wunused-parameter]
 1018 | void HAL_RCC_MCOConfig(uint32_t RCC_MCOx, uint32_t RCC_MCOSource, uint32_t RCC_MCODiv)
      |                        ~~~~~~~~~^~~~~~~~
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal_rcc_ex.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal_rcc_ex.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c -o build-canable/stm32f0xx_hal_rcc_ex.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c -o build-canable/stm32f0xx_hal.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal_gpio.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal_gpio.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c -o build-canable/stm32f0xx_hal_gpio.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal_cortex.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal_cortex.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c -o build-canable/stm32f0xx_hal_cortex.o
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c: In function 'HAL_NVIC_SetPriority':
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c:136:78: warning: unused parameter 'SubPriority' [-Wunused-parameter]
  136 | void HAL_NVIC_SetPriority(IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)
      |                                                                     ~~~~~~~~~^~~~~~~~~~~
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/stm32f0xx_hal_can.d" -Wa,-a,-ad,-alms=build-canable/stm32f0xx_hal_can.lst Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.c -o build-canable/stm32f0xx_hal_can.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/usbd_core.d" -Wa,-a,-ad,-alms=build-canable/usbd_core.lst Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c -o build-canable/usbd_core.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/usbd_ctlreq.d" -Wa,-a,-ad,-alms=build-canable/usbd_ctlreq.lst Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c -o build-canable/usbd_ctlreq.o
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c: In function 'USBD_CtlError':
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c:853:42: warning: unused parameter 'req' [-Wunused-parameter]
  853 |                    USBD_SetupReqTypedef *req)
      |                    ~~~~~~~~~~~~~~~~~~~~~~^~~
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/usbd_ioreq.d" -Wa,-a,-ad,-alms=build-canable/usbd_ioreq.lst Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c -o build-canable/usbd_ioreq.o
arm-none-eabi-gcc -x assembler-with-cpp -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F042x6 -DNDEBUG  -ISrc -IDrivers/STM32F0xx_HAL_Driver/Inc -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Os -Wall -Wpedantic -Wextra -fno-common -fdata-sections -ffunction-sections -std=c99  -MMD -MP -MF"build-canable/startup_stm32f042x6.d" startup_stm32f042x6.s -o build-canable/startup_stm32f042x6.o
arm-none-eabi-gcc build-canable/main.o build-canable/usbd_conf.o build-canable/usbd_desc.o build-canable/pcan_usb.o build-canable/pcan_can.o build-canable/pcan_led.o build-canable/pcan_protocol.o build-canable/pcan_timestamp.o build-canable/system_stm32f0xx.o build-canable/stm32f0xx_ll_usb.o build-canable/stm32f0xx_hal_pcd.o build-canable/stm32f0xx_hal_pcd_ex.o build-canable/stm32f0xx_hal_rcc.o build-canable/stm32f0xx_hal_rcc_ex.o build-canable/stm32f0xx_hal.o build-canable/stm32f0xx_hal_gpio.o build-canable/stm32f0xx_hal_cortex.o build-canable/stm32f0xx_hal_can.o build-canable/usbd_core.o build-canable/usbd_ctlreq.o build-canable/usbd_ioreq.o build-canable/startup_stm32f042x6.o -mcpu=cortex-m0 -mthumb   -specs=nano.specs -TSTM32F042C6Tx_FLASH.ld  -lc -lm -lnosys  -Wl,-Map=build-canable/pcan_canable_hw.map,--cref -Wl,--gc-sections -o build-canable/pcan_canable_hw.elf
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: build-canable/pcan_canable_hw.elf section `.data' will not fit in region `FLASH'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 108 bytes
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:175: build-canable/pcan_canable_hw.elf] Error 1
make[1]: Leaving directory '/home/kadir/Downloads/pcan_cantact-master'
make: *** [Makefile:152: canable] Error 2
`
When I just type canable or cantact-16 Im getting this error. Im using ubuntu 20.04.3 64 bit intel i7-11370H and uname -r output : 5.11.0-40-generic

**Comment by moonglow** [comment]
Hi @kadirtunc 

Please read **this**:  [LINK](https://github.com/moonglow/pcan_cantact/discussions/9)

You toolchain just produce bigger code...

**Comment by kadirtunc** [comment]
Could you please give an instruction to update or install your test toolchain?

**Comment by moonglow** [comment]
Which MCU you use ? It needs only for low end 16K flash MCU ( all other MCU with bigger flash will compiled OK you need just increse flash size in linker script ). And you can download latest toolchain by yourself and use it to compile project then you need to set GCC_PATH which Makefile uses to locate toolchain....

p.s: but i recomends you to use precompiled versions from Release page.
