### ISSUE TITLE
minor : some leftover I2C stuff

### ISSUE THREAD

**Issue by fenugrec** [moonglow/pcan_cantact#13]
Cool project !
I took about 15 minutes to port it to my F042 board, seems to be working so far.
Looking through the code :

```
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USB|RCC_PERIPHCLK_I2C1;
  PeriphClkInit.UsbClockSelection = RCC_USBCLKSOURCE_HSI48;
  PeriphClkInit.I2c1ClockSelection = RCC_I2C1CLKSOURCE_HSI;
  HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit);
```

We can probably remove everything related to I2C ? Unless there's a non-obvious usage that I missed...

**Comment by moonglow** [comment]
Thanx @fenugrec !

>We can probably remove everything related to I2C ? 

Yeh it is rudiment part,it do nothing here.. you can remove it, but it will not change anything.

**Comment by moonglow** [comment]
done
