### ISSUE TITLE
Ollie Pcan firmware [PCAN DRIVER >= 4.3.x ISSUE]

### ISSUE THREAD

**Issue by killisch** [moonglow/pcan_cantact#14]
Hi i'm trying use an Ollie USB-can device. https://github.com/slimelec/ollie-hw
They provide a forked version of your PCAN firmware. i have tried both your version and their provided version.
the device is recognized as  the pcan adapter in device manager.
but no traffic can be sent or received.
If i unplug the usb cable and plug it back in data is received for between 100-200ms then stops. no errors are present in the PCAN software.
have you run into any similar issues?

**Comment by killisch** [comment]
To add to this. if i load the standard firmware for the device (non Pcan) i can send and receive can traffic. but the software i need to use for my application requires a PCan adapter.

**Comment by moonglow** [comment]
@killisch you need to ask @slimelec directly i think... i never has his board on my hands ,but if you will saw his [commit](https://github.com/slimelec/pcan_cantact/commit/6d8646835b8c578c9f494e1e7c8ece89fd019089) you need to preconfigured some pins to enable needed voltage switcher and all be OK i think. I think i will add some feature to easy makes special boards supported too as it was done for PCAN PRO X firmware. Anyway why you do not want to use his forked version ?

**Comment by moonglow** [comment]
Another thing if your adapter does not connected to bus ( and no one will receive frames ) you will get FIFO overrun because frames does not comes out from your adapter... maybe you have such problem... anyway my solution is really well tested and shows very stable in real cases.

**Comment by slimelec** [comment]
@moonglow the issues seems to be the latest pcan drivers. This was resolved by installing older drivers see [Issue](https://github.com/slimelec/ollie-hw/issues/8#issuecomment-1016068990) .

Btw nothing special about my adapter CAN side of things, I just enable few IO.

**Comment by moonglow** [comment]
@slimelec  Thank you ! need to check whats they changed.... 

p.s: your adapter is nice, but i just does not have it :) that's why i can't provide correct support for that issue

**Comment by slimelec** [comment]
@moonglow oh no! If you like drop me a message with your details and I'll get you sorted :) 
https://www.meatpi.com/contact

**Comment by moonglow** [comment]
@killisch @slimelec 

can you check latest builds ( [v1.6](https://github.com/moonglow/pcan_cantact/releases/tag/v1.6) )
