### ISSUE TITLE
Canable build is not working after 10sec

### ISSUE THREAD

**Issue by kadirtunc** [moonglow/pcan_cantact#15]
Hi. I installed canable firmware. It works. PCANView sees my hardware as PCAN. But there is an issue. After 10sec It is not blinking anymore. It can not transmit or receive data. Is this issue about new driver that PEAK systems released ?

**Comment by moonglow** [comment]
Hi !

You can try to get older drivers from here to check that [LINK](https://github.com/slimelec/ollie-hw/issues/8#issuecomment-1016068990)

p.s: looks like i already know what they did... so maybe i will update firmware soon too

**Comment by kadirtunc** [comment]
I am waiting your update. Thank you for answer.

**Comment by moonglow** [comment]
@kadirtunc 

can you check latest builds ( [v1.6](https://github.com/moonglow/pcan_cantact/releases/tag/v1.6) )
