### ISSUE TITLE
The latest version (V1.6) problem still exists

### ISSUE THREAD

**Issue by ChengHero** [moonglow/pcan_cantact#17]
The latest version (V1.6) problem still exists, my hardware is canable, similar to the problem of killisch, it has not been repaired after flashing V1.6, and there is a problem with the cycle sending, and the cycle is unstable. Sorry for my bad english.

**Comment by ChengHero** [comment]
Regarding the issue of periodic sending, it should be my wrong operation, sorry

**Comment by moonglow** [comment]
Hi @ChengHero !

You have such issue on new 4.3.0 drivers and if you install previous version of drivers ( from that thread:  [LINK](https://github.com/slimelec/ollie-hw/issues/8#issuecomment-1016068990) ) all is OK ? Because i have no problem with new drivers for now, maybe i need to do more testing.

**Comment by ChengHero** [comment]
hi @moonglow 
thank you ！！maybe my problem，I will try it on version 4.3.0

**Comment by moonglow** [comment]
Hm.. can you provide me more info:

- PCAN driver version
- Operating System

thank you

**Comment by ChengHero** [comment]
Reinstalling 4.3.0 doesn't work either，My hardware is not orthodox, the soc is STM32F072, I don't know if it will affect。I think it should be my hardware problem。Operating System is windows 10。

**Comment by ChengHero** [comment]
My canable hardware is personally designed with reference to the canable hardware on github

**Comment by moonglow** [comment]
So your adapter is connected to bus and work only few second ? correct ?

**Comment by ChengHero** [comment]
Worked for a split second before, not for a few seconds

**Comment by moonglow** [comment]
Your adapter is connected to active CAN bus ?

**Comment by ChengHero** [comment]
I tested it with PEAK-PCAN and it is OK

**Comment by moonglow** [comment]
So now all is OK ?

**Comment by ChengHero** [comment]
It still doesn't work, but it's ok to use genuine hardware

**Comment by moonglow** [comment]
Ah...  OK, thank you. Please try old drivers as temporary solution.

**Comment by ChengHero** [comment]
thank you！！

**Comment by ChengHero** [comment]
hi ... @moonglow ，I tried to downgrade the driver version to 3.4.0.9248, the problem was solved, thank you

**Comment by moonglow** [comment]
I did try to upload canable precompiled firmware from my release page and it works fine with latest `4.3.0.16563` drivers under Windows 10 x64 with `PCAN View` and `BusMaster`. I test over few hours and it works just fine.

**Comment by ChengHero** [comment]
I think so too, the device is working very well, there are only some occasional problems after that, thank you

**Comment by P208PUG** [comment]
> I did try to upload canable precompiled firmware from my release page and it works fine with latest `4.3.0.16563` drivers under Windows 10 x64 with `PCAN View` and `BusMaster`. I test over few hours and it works just fine.

is possible to get a precompiled bin(pcan) for candlelight hw
