### ISSUE TITLE
J2534

### ISSUE THREAD

**Issue by Memfispro** [moonglow/pcan_cantact#4]
Hello. I have been using your device for a long time. I just want to clarify if you have implemented the j2534 mode? For some reason I was unable to use j2534.

**Comment by moonglow** [comment]
Hi ! Did you try latest version ? It was fixes some data transfer issue. J2534 is hi level protocol so i think it must be OK

**Comment by Memfispro** [comment]
Yes, the latest firmware version. The driver recognizes well, but there is an error_invalid _channel_id error. The program that shows errors DrewTechToolForJ2534.

**Comment by moonglow** [comment]
Hm, looks strange if you can share that utility i can try to look

**Comment by Memfispro** [comment]
Sent to you by mail.

**Comment by moonglow** [comment]
>error serial number. The program that shows errors DrewTechToolForJ2534.

Can you also shows me screenshots step by step to reproduce it. Thanx.
