### ISSUE TITLE
F042 availability is BAAAAAAD any chance to support F103?

### ISSUE THREAD

**Issue by rusefillc** [moonglow/pcan_cantact#5]
Is there any interest to support F103 since it's available while F042 availability is horrible at the moment?

I even have a tiny open source board with CAN and F103 if that would help :)

**Comment by moonglow** [comment]
Андрей, привествую ! К сожалению F103 не может одновременно использовать USB + CAN так-как эти блоки используют одну и ту же область памяти. Как вариант есть более доступный F407 дешево и сердито и поддерживается сразу 2 канала на прошивках PCAN/Vector. F042 можно заменить на F072 и т.д...  в настоящее время практически все микроконтроллеры в дефиците... 

----
Hi! Nope, sorry. F103 uses same shared memory area for both peripheral blocks USB + CAN, so they can't be used simultaneously.

**Comment by rusefillc** [comment]
Мне нравится вариант F407, есть ли какие-то ссылки на эту тему? :)

Я слежу за доступностью чипив https://github.com/andreika-git/hellen-one/issues/19 и некоторые чипы сильно доступнее других: 407-100 очень доступен, 144 достаточно доступен. 176 уже сложнее, но есть варианты. 

F042 ОЧЕНЬ непросто купить.

**Comment by rusefillc** [comment]
is it https://github.com/moonglow/pcan_pro_x for PCAN on F4?

**Comment by moonglow** [comment]
@rusefillc 

На F407:
https://github.com/moonglow/pcan_pro_x - Да, это прошивка имитирующая PCAN PRO/PRO FD рекомендую собирать версию под PROFD так-как их драйвер более оптимизирован мне показался для передачи много данных (  конечно самих FDCAN фреймов там не будет в виду того, что их не поддерживает само железо ).

https://github.com/moonglow/vector_can - Прошивка имитирующая VN1610 от Vector, тоже два канала.

**Comment by dron0gus** [comment]
Прошу прощения, что влезаю.
Китайцы продают CANdo адаптер. https://aliexpress.ru/item/4001164534407.html Он на клоне STM32F103 - GD32E103. Он работает. Т.е. одновременно и CAN и USB.
И есть еще один вариант на али. Тот приходит с чипом с маркировкой STM32F103 (не факт, что не перемаркирован). Его я еще не успел проверить.

**Comment by rusefillc** [comment]
https://rusefi.com/forum/viewtopic.php?p=43128#p43128 mentions F103 hacks

**Comment by moonglow** [comment]
@dron0gus Ценник конечно высокий, почти такой же как и на отладку на F407, где возможностей будет больше.
По поводу использования одновременно USB + CAN на китайском клоне GD32E103 я ознакомлюсь, спасибо.

@rusefillc Переключаться между интерфейсами можно ( вначале работает одно, а потом другое ), но это конечно еще тот трюк... я надеюсь, что дифицит чипов не доведет нас до таких решений ^_^

**Comment by rusefillc** [comment]
@moonglow 100% согласен, что тинамическое переопределение фунцуций пинов это уже за гранью

**Comment by dron0gus** [comment]
@rusefillc с пинами нет проблем. Все растаскивается на разные группы https://electronix.ru/forum/index.php?app=forums&module=forums&controller=topic&id=78631 .
Проблема именно в общей памяти, где USB располагает буфера, а CAN - mailboxes.

**Comment by dron0gus** [comment]
@moonglow ценник не сравним с оригинальным PEAK PCAN, например. По сравнению с отладкой паять не надо. То что надо для пользователей.

**Comment by moonglow** [comment]
@dron0gus когда я опубликовал свой проект, то и это решение было достаточно дешевым ( как Kvaser/PCAN адаптер ) так и на F407 ( PCAN/Vector ). Единственный плюс в том, что там уже готовая плата, но вопрос все же больше в софте чем в железе. На Али любой даже самый тривиальный CAN адаптер стоит достаточно дорого, возможно стоит рассмотреть вариант с альтернативным общедоступным контроллером и кастомной платой.

**Comment by dron0gus** [comment]
@moonglow у нас все очень запутано. Лишь @rusefillc видит картину в целом. Нам надо чтобы пользователи могли обновлять/настраивать RusEFI через недорогой адаптер.
К сожалению пользователи неразумные и сидят под виндой, а то и под маком. Поэтому мы хотим что-то, что прикидывается PCAN'ом например.
Тот адатер с Али под линуксом заработал "из коробки". И меня он полностью устраивает as-is.
С другой стороны делать свой адаптер - можно, но это лишний геморой с непонятным профитом. :)
К прошивалщику можно вообще прикрутить копеечный ELM327. Только вот ничего кроме прошивки через него делать невозможно. :)
